BUILDER_VERSION = 104

XML_2_BIN_DLL_PATH = "ToolsXmlCodecPlugin.dll"

CREATE_ATLAS_FOR_MOVIE = 1
CREATE_ATLAS_NONE = 0

PACK_EXTENSION = "pak"
PACK_TYPE = "zip"

BIN_EXTENSION = "bin"

IMAGE_MODE_CONVERT_NO_CONVERT = 0
IMAGE_MODE_CONVERT_PNG_TO_WEBP = 1
IMAGE_MODE_CONVERT_PNG_TO_ETC1 = 2
IMAGE_MODE_CONVERT_PNG_TO_PVRTC = 3
IMAGE_MODE_CONVERT_PNG_TO_DXT1 = 4
IMAGE_MODE_CONVERT_PNG_TO_WEBP_AND_ETC1 = 5

SOUND_MODE_CONVERT_TO_OGG = 0
SOUND_MODE_CONVERT_TO_AAC = 1
SOUND_MODE_CONVERT_TO_WAV = 2
SOUND_MODE_CONVERT_TO_MP3 = 3

MUSIC_MODE_CONVERT_TO_OGG = 0
MUSIC_MODE_CONVERT_TO_AAC = 1
MUSIC_MODE_CONVERT_TO_MP3 = 2

EXE_FILE_COMPANY = "Menge"
EXE_FILE_VERSION = "1.2.3.4"

ERROR_REPORTING_SILENT = 1
ERROR_REPORTING_VERBOSE = 2
ERROR_REPORTING_DEFAULT = 3

ICONS_NAME = "ICON"

ATLAS_TEXTURE_TYPE = "RGBA"
ATLAS_IMAGE_TYPE = "png"
ATLAS_FILL_COLOR = (0,0,0,0)
ATLAS_TEXTURE_BORDER_SIZE = 2
ATLAS_FOLDER = "Atlas"
ATLAS_NAME_IF_SCENE_NAME_IS_EMPTY = "Unknown"
